const B = 'http://localhost:3999';
const assert = (c, m) => { if (!c) { console.log('FAIL:', m); process.exitCode = 1; } else console.log('ok  ', m); };
let ck = ''; const f = async (p, o = {}) => { const r = await fetch(B + p, { ...o, headers: { 'content-type': 'application/json', cookie: ck, ...(o.headers || {}) } }); const sc = r.headers.get('set-cookie'); if (sc && sc.startsWith('jp_session')) ck = sc.split(';')[0]; const t = await r.text(); try { return { s: r.status, j: JSON.parse(t) }; } catch { return { s: r.status, t }; } };
const post = (p, b) => f(p, { method: 'POST', body: JSON.stringify(b) });
const sleep = (t) => new Promise((r) => setTimeout(r, t));
(async () => {
  await post('/api/signup', { country: 'GB', email: 'hook@x.com', password: 'password1' });
  let r = await post('/api/bot-targets/external', { username: 'mystore' });
  assert(r.s === 400, 'username must end in bot');
  r = await post('/api/bot-targets/external', { username: '@MyStore_bot' });
  assert(r.j.ok && /\/hook\/[\w-]+\/start$/.test(r.j.hook_start), 'external bot created without a token, hook URL returned');
  const hook = new URL(r.j.hook_start).pathname, hookB = new URL(r.j.hook_blocked).pathname;
  const ch = (await f('/api/channels')).j.channels.find((c) => c.external);
  assert(ch && ch.status === 'active' && ch.type === 'bot', 'shows in Channels as an active bot target');
  await f('/api/channels/' + ch.id, { method: 'PATCH', body: JSON.stringify({ pixel_id: '884210395527140', capi_token: 'EAAtest' }) });
  const go = await fetch(B + new URL(ch.tracking_url).pathname + '/go', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{"url":"https://x.com/?fbclid=FBX&utm_campaign=Hooked"}' }).then((x) => x.json());
  console.log(go); assert(/^https:\/\/t\.me\/MyStore_bot\?start=/.test(go.url), 'tracking link opens their bot with a start code');
  const code = new URL(go.url).searchParams.get('start');
  r = await fetch(B + hook, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ bot: 'mystore_bot', start: code, user: { id: 9911, first_name: 'Mia', username: 'mia' } }) }).then((x) => x.json());
  assert(r.ok && r.from_ad, 'bot reports Start (JSON) → matched to the ad');
  r = await fetch(B + hook + `?bot=MyStore_bot&text=${encodeURIComponent('/start ' + code)}&tg_id=9911`).then((x) => x.json());
  assert(r.ok && r.duplicate, 'repeat Start is not counted twice (GET, raw /start text)');
  r = await fetch(B + hook + `?bot=mystore_bot&tg_id=9922&first_name=Omar&start=`).then((x) => x.json());
  assert(r.ok && !r.from_ad, 'Start without a code counts as organic');
  r = await fetch(B + hook + `?bot=otherbot_bot&tg_id=1`).then((x) => x.json());
  assert(r.ok === false, 'unknown bot rejected');
  r = await fetch(B + hookB + `?bot=mystore_bot&tg_id=9911`).then((x) => x.json());
  assert(r.left, 'blocked bot = left');
  await sleep(2600);
  const d = new Date().toISOString().slice(0, 10);
  const jr = (await f(`/api/joins?from=${d}&to=${d}&tz=0`)).j;
  const mia = jr.rows.find((x) => x.first_name === 'Mia');
  assert(jr.total === 2 && mia.click_id && mia.capi_status === 'sent' && mia.left_at && mia.params.utm_campaign === 'Hooked', 'dashboard shows both people; Mia from ad, sent to Meta, left');
  const st = (await f(`/api/stats?from=${d}&to=${d}&tz=0`)).j.totals;
  assert(st.joins === 1 && st.organic === 1 && st.leaves === 1, 'stats count it like any join');
})();
