const B = 'http://localhost:3999';
const assert = (c, m) => { if (!c) { console.log('FAIL:', m); process.exitCode = 1; } else console.log('ok  ', m); };
let ck = ''; const f = async (p, o = {}) => { const r = await fetch(B + p, { ...o, headers: { 'content-type': 'application/json', cookie: ck, ...(o.headers || {}) } }); const sc = r.headers.get('set-cookie'); if (sc && sc.startsWith('jp_session')) ck = sc.split(';')[0]; const t = await r.text(); try { return { s: r.status, j: JSON.parse(t) }; } catch { return { s: r.status, t }; } };
const post = (p, b) => f(p, { method: 'POST', body: JSON.stringify(b) });
const ms = () => fetch('http://localhost:4000/__state').then((r) => r.json()); const sleep = (t) => new Promise((r) => setTimeout(r, t));
(async () => {
  await post('/api/signup', { country: 'GB', email: 'ftd@x.com', password: 'password1' });
  let r = await post('/api/bots', { token: '7712045533:AAHk3vZq_testtokenxxxxxxxxxxxxxxxxx' });
  const st = await ms(); const H = { 'x-telegram-bot-api-secret-token': st.webhook.secret_token }, hook = new URL(st.webhook.url).pathname;
  await post('/api/bot-targets', { bot_id: r.j.bot.id });
  const ch = (await f('/api/channels')).j.channels[0];
  r = await f('/api/channels/' + ch.id, { method: 'PATCH', body: JSON.stringify({ platform: 'snap', sc_pixel: 'not-a-uuid', sc_token: 'x' }) });
  assert(r.s === 400, 'bad Snap pixel id rejected');
  await f('/api/channels/' + ch.id, { method: 'PATCH', body: JSON.stringify({ platform: 'snap', sc_pixel: '1a2b3c4d-1234-5678-9abc-def012345678', sc_token: 'snaptok' }) });
  await f('/api/channels/' + ch.id, { method: 'PATCH', body: JSON.stringify({ pixel_id: '884210395527140', capi_token: 'EAAtest' }) });
  r = await post('/api/channels/' + ch.id + '/test?platform=snap', {});
  assert(r.s === 200 && /validate/.test((await ms()).snapUrl), 'Snapchat test event uses validation endpoint');
  const slug = new URL(ch.tracking_url).pathname;
  const html = await fetch(B + slug).then((x) => x.text());
  assert(/sc-static\.net\/scevent\.min\.js/.test(html) && /snaptr\('init','1a2b3c4d/.test(html), 'tracking page loads the Snap pixel');
  const go = await fetch(B + slug + '/go', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ url: 'https://x.com' + slug + '?ScCid=SC123&utm_campaign=Spring&utm_content=Video1&fbclid=FB1', scid: 'scid-cookie' }) }).then((x) => x.json());
  const code = new URL(go.url).searchParams.get('start');
  await f(hook, { method: 'POST', headers: H, body: JSON.stringify({ update_id: 500, message: { message_id: 1, date: 1, chat: { id: 4242, type: 'private' }, from: { id: 4242, first_name: 'Mia' }, text: '/start ' + code } }) });
  await f(hook, { method: 'POST', headers: H, body: JSON.stringify({ update_id: 500, message: { message_id: 1, date: 1, chat: { id: 4242, type: 'private' }, from: { id: 4242, first_name: 'Mia' }, text: '/start ' + code } }) });
  await sleep(2600);
  let s2 = await ms();
  const snapJoin = (s2.snap || []).find((e) => e.event_name === 'SUBSCRIBE' && /^tgjoin_/.test(e.event_id));
  assert(snapJoin && snapJoin.user_data.sc_click_id === 'SC123' && snapJoin.user_data.sc_cookie1 === 'scid-cookie' && snapJoin.action_source === 'WEB', 'join sent to Snapchat with click id + cookie');
  const d = new Date().toISOString().slice(0, 10);
  let jr = (await f(`/api/joins?from=${d}&to=${d}&tz=0`)).j;
  assert(jr.total === 1 && jr.rows[0].sc_status === 'sent', 'repeat Telegram update ignored, Snap status sent');
  // postback
  const pb = (await f('/api/conversions')).j.postback_url;
  assert(/\/pb\/[\w-]+$/.test(pb), 'account has a postback URL');
  const pbPath = new URL(pb).pathname;
  r = await fetch(B + pbPath + '?sub1=4242&status=reg').then((x) => x.json());
  assert(r.ok && r.matched && r.event === 'reg', 'registration postback matched by Telegram id');
  r = await fetch(B + pbPath + '?sub1=4242&status=deposit&payout=120.50&currency=usd&txid=T1').then((x) => x.json());
  assert(r.ok && r.event === 'ftd', 'first deposit (sent as "deposit") becomes FTD');
  r = await fetch(B + pbPath + '?sub1=4242&status=deposit&payout=120.50&txid=T1').then((x) => x.json());
  assert(r.duplicate, 'same transaction id is not counted twice');
  r = await fetch(B + pbPath, { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: 'tg_id=4242&event=ftd&amount=30&txid=T2' }).then((x) => x.json());
  assert(r.ok && r.event === 'dep', 'second deposit is a repeat deposit, even if called ftd (POST form)');
  r = await fetch(B + pbPath + '?sub1=999999&status=ftd&payout=10').then((x) => x.json());
  assert(r.ok && r.matched === false, 'unknown user is logged as unmatched');
  r = await fetch(B + pbPath + '?sub1={sub1}&status=ftd').then((x) => x.json());
  assert(r.ok && r.matched === false, 'unfilled macro is ignored');
  r = await fetch(B + '/pb/wrongkey12345?sub1=4242&status=ftd');
  assert(r.status === 404, 'wrong postback key refused');
  await sleep(2600);
  s2 = await ms();
  const metaP = s2.events.find((e) => e.event_name === 'Purchase' && e.custom_data && e.custom_data.value === 120.5);
  assert(metaP && metaP.custom_data.currency === 'USD' && metaP.user_data.fbc, 'FTD sent to Meta as Purchase with value and click id');
  assert(s2.events.some((e) => e.event_name === 'CompleteRegistration'), 'registration sent to Meta');
  assert(s2.events.some((e) => e.event_name === 'Deposit' && e.custom_data.value === 30), 'repeat deposit sent to Meta as Deposit');
  assert((s2.snap || []).some((e) => e.event_name === 'PURCHASE' && e.custom_data.value === 120.5), 'FTD sent to Snapchat as PURCHASE');
  const conv = (await f('/api/conversions')).j.rows;
  assert(conv.length === 5 && conv.find((c) => c.event === 'ftd' && c.matched).meta_status === 'sent', 'conversion log shows statuses');
  // manual FTD on another person
  await f(hook, { method: 'POST', headers: H, body: JSON.stringify({ update_id: 501, message: { message_id: 2, date: 1, chat: { id: 5151, type: 'private' }, from: { id: 5151, first_name: 'Lucas' }, text: '/start' } }) });
  jr = (await f(`/api/joins?from=${d}&to=${d}&tz=0`)).j;
  const lucas = jr.rows.find((x) => x.first_name === 'Lucas');
  r = await post(`/api/joins/${lucas.id}/convert`, { event: 'ftd', value: '45' });
  assert(r.j.ok && r.j.attributed === false, 'manual FTD on an organic person recorded, not sent');
  jr = (await f(`/api/joins?from=${d}&to=${d}&tz=0&type=ftd`)).j;
  assert(jr.total === 2, 'People filter: depositors');
  const stt = (await f(`/api/stats?from=${d}&to=${d}&tz=0`)).j.totals;
  assert(stt.ftd === 2 && stt.reg === 1 && stt.revenue_cents === 12050 + 3000 + 4500, 'stats count FTDs, registrations and revenue (' + JSON.stringify(stt) + ')');
  const cmp = (await f('/api/compare?months=6&tz=0')).j.months;
  const cur = cmp[cmp.length - 1];
  assert(cmp.length === 6 && cur.joins === 1 && cur.ftd === 2 && cur.partial, 'month comparison returns 6 months with this month partial');
  const bd = (await f(`/api/breakdown?dim=campaign&from=${d}&to=${d}&tz=0`)).j.rows;
  assert(bd[0].key === 'Spring' && bd[0].joins === 1 && bd[0].ftd === 1 && bd[0].revenue_cents === 15050, 'campaign breakdown with FTD + revenue');
  const bp = (await f(`/api/breakdown?dim=platform&from=${d}&to=${d}&tz=0`)).j.rows;
  assert(bp[0].key === 'Meta', 'platform breakdown');
  const csv = await fetch(B + `/api/joins.csv?from=${d}&to=${d}&tz=0`, { headers: { cookie: ck } }).then((x) => x.text());
  assert(/first_deposit/.test(csv) && /120\.5/.test(csv), 'CSV has deposit columns');
  // support chat: visitor + user + admin
  let vck = ''; const vf = async (p, o = {}) => { const r = await fetch(B + p, { ...o, headers: { 'content-type': 'application/json', cookie: vck } }); const sc = r.headers.get('set-cookie'); if (sc) vck = sc.split(';')[0]; return { s: r.status, j: await r.json() }; };
  r = await vf('/api/support', { method: 'POST', body: JSON.stringify({ body: 'Hi, is TikTok supported?' }) });
  assert(r.s === 400 && r.j.need_email, 'visitor must leave an email on first message');
  r = await vf('/api/support', { method: 'POST', body: JSON.stringify({ body: 'Hi, is TikTok supported?', email: 'visitor@y.com' }) });
  assert(r.j.ok, 'visitor message sent');
  r = await post('/api/support', { body: 'My channel is not showing up' });
  assert(r.j.ok, 'logged-in user message sent');
  let ADMck = ''; const af = async (p, o = {}) => { const r = await fetch(B + p, { ...o, headers: { 'content-type': 'application/json', cookie: ADMck } }); const sc = r.headers.get('set-cookie'); if (sc && sc.startsWith('jp_session')) ADMck = sc.split(';')[0]; return { s: r.status, j: await r.json().catch(() => ({})) }; };
  await af('/api/signup', { method: 'POST', body: JSON.stringify({ country: 'GB', email: 'admin@x.com', password: 'password1' }) });
  await sleep(100);
  const vlink = [...require('fs').readFileSync(process.env.SRV_LOG, 'utf8').matchAll(/to admin@x\.com .*?(\/verify\?t=[\w.-]+)/g)].pop();
  await fetch(B + vlink[1], { redirect: 'manual' });
  const tk = (await af('/api/admin/support')).j.tickets;
  assert(tk.length === 2 && tk.every((t) => t.unread_admin === 1), 'admin inbox shows both conversations unread');
  const vt = tk.find((t) => t.email === 'visitor@y.com');
  await af('/api/admin/support/' + vt.id, { method: 'POST', body: JSON.stringify({ body: 'Yes! TikTok and Snapchat both work.' }) });
  r = await vf('/api/support');
  assert(r.j.messages.length === 2 && r.j.messages[1].from_admin === 1 && r.j.online, 'visitor sees the reply, admin shown online');
  r = await f('/api/support');
  assert(r.j.messages.length === 1 && r.j.messages[0].body.includes('channel'), 'user sees only their own conversation');
  assert((await af('/api/admin/overview')).j.support_unread === 1, 'overview counts unread conversations');
})();
